#!/bin/bash

usage() {
    echo "Usage: $0 [ -n RANKS ] [ -H HOSTS ] psana://<exp>:<run>" 1>&2
}

NUMARGS=$#
if [ $NUMARGS -ne 5 ]; then
    usage
    exit 1
fi

while getopts n:H: flag
do
    case "${flag}" in
        n) ranks=${OPTARG};;
        H) workers=${OPTARG};;
    esac
done

IFS=', ' read -r -a array <<< "$workers"
num_worker_nodes=${#array[@]}

shift $(($OPTIND - 1))
rest=$@

manager=`hostname`
echo "ranks: $ranks";
echo "workers: $workers";
echo "num worker nodes: $num_worker_nodes"
echo "manager: $manager";
ami-manager -n $ranks -N $num_worker_nodes &
MANAGER_PID=$!
ami-global -N 0 -n $num_worker_nodes -H $manager &
GLOBAL_PID=$!
`which mpirun` -np $ranks -H $workers -x LD_LIBRARY_PATH -x PYTHONPATH -x PATH ami-remote -H $manager -f interval=0.01 -f repeat=True $@ &
WORKER_PID=$!

echo "manager: $MANAGER_PID";
echo "global: $GLOBAL_PID";
echo "worker: $WORKER_PID";

trap onexit INT
function onexit() {
    kill -9 $MANAGER_PID
    kill -9 $GLOBAL_PID
    kill -9 $WORKER_PID
}

ami-client -H $manager
onexit
