name: Test AMI
on:
  schedule:
    - cron: '0 5 * * *'  # once per day at midnight ET
  workflow_dispatch:

jobs:
  build-lcls-ii:
    runs-on: ubuntu-latest
    defaults:
     run:
       # Bash shells do not use ~/.profile (for env variables) or ~/.bashrc,
       # so these shells need to be explicitly declared.
       # This makes the shell a login shell, which typically
       # sources said files. This is needed for conda.
       # Refer: https://github.com/marketplace/actions/setup-miniconda
       shell: bash -el {0}  
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: build-conda-env
          channels: lcls-ii, conda-forge
          environment-file: .daq_20250402.txt

      - name: Clone LCLS2
        run:
          git clone https://github.com/slac-lcls/lcls2.git
          cd lcls2
          ./build_all.sh -c {Release, Debug, RelWithDebInfo} -p {develop, install}
          cd ..
      
      - name: Build AMI
        run:
          ls
          ./build_all.sh
